//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STRAINER_EXTRACT.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AR,GI,GR,IP,PR,RC,RG,RV,")]
        public string FOLDERS {
            get {
                return ((string)(this["FOLDERS"]));
            }
            set {
                this["FOLDERS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\DropsiteTemp\\")]
        public string FOR_SYNC_FOLDER {
            get {
                return ((string)(this["FOR_SYNC_FOLDER"]));
            }
            set {
                this["FOR_SYNC_FOLDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\TempPath\\")]
        public string TEMP_FOLDER {
            get {
                return ((string)(this["TEMP_FOLDER"]));
            }
            set {
                this["TEMP_FOLDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\TestPath\\")]
        public string DROPSITE_FOLDER {
            get {
                return ((string)(this["DROPSITE_FOLDER"]));
            }
            set {
                this["DROPSITE_FOLDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ARStored_1,ARStored_2,ARStored_4")]
        public string AR_STORED_PROC {
            get {
                return ((string)(this["AR_STORED_PROC"]));
            }
            set {
                this["AR_STORED_PROC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GIStored_1_Ref,GIStored_2_Ref")]
        public string GI_STORED_PROC {
            get {
                return ((string)(this["GI_STORED_PROC"]));
            }
            set {
                this["GI_STORED_PROC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GRStored_1_Ref,GRStored_2_Ref")]
        public string GR_STORED_PROC {
            get {
                return ((string)(this["GR_STORED_PROC"]));
            }
            set {
                this["GR_STORED_PROC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PRStored_1_Ref, PRStored_2_Ref")]
        public string PR_STORED_PROC {
            get {
                return ((string)(this["PR_STORED_PROC"]));
            }
            set {
                this["PR_STORED_PROC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RCStored_1,RCStored_2,RCStored_4")]
        public string RC_STORED_PROC {
            get {
                return ((string)(this["RC_STORED_PROC"]));
            }
            set {
                this["RC_STORED_PROC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RGStored_1_Ref,RGStored_2_Ref")]
        public string RG_STORED_PROC {
            get {
                return ((string)(this["RG_STORED_PROC"]));
            }
            set {
                this["RG_STORED_PROC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RVStored_1_Ref,RVStored_2_Ref")]
        public string RV_STORED_PROC {
            get {
                return ((string)(this["RV_STORED_PROC"]));
            }
            set {
                this["RV_STORED_PROC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IPStored_5")]
        public string IP_STORED_PROC {
            get {
                return ((string)(this["IP_STORED_PROC"]));
            }
            set {
                this["IP_STORED_PROC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ARStored_5,ARStored_6,ARStored_8")]
        public string AR_STORED_PROC2 {
            get {
                return ((string)(this["AR_STORED_PROC2"]));
            }
            set {
                this["AR_STORED_PROC2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AR,IP,RC")]
        public string GENERATION_BY_BATCH {
            get {
                return ((string)(this["GENERATION_BY_BATCH"]));
            }
            set {
                this["GENERATION_BY_BATCH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AR_IP_MEM_CASH_1,AR_IP_MemStored_3")]
        public string AR_STORED_PROC3 {
            get {
                return ((string)(this["AR_STORED_PROC3"]));
            }
            set {
                this["AR_STORED_PROC3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AR_IP_NM_CASH_2,AR_IP_NMStored_4")]
        public string AR_STORED_PROC4 {
            get {
                return ((string)(this["AR_STORED_PROC4"]));
            }
            set {
                this["AR_STORED_PROC4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ARWSStored_1,ARWSStored_2,ARWSStored_4")]
        public string AR_PAIWI_STORED {
            get {
                return ((string)(this["AR_PAIWI_STORED"]));
            }
            set {
                this["AR_PAIWI_STORED"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=localhost;Database=_pallocan;Username=root;Password=supervisor;")]
        public string DB {
            get {
                return ((string)(this["DB"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Projecterp\\pallocan\\")]
        public string FOR_FINAL_SYNC_FOLDER {
            get {
                return ((string)(this["FOR_FINAL_SYNC_FOLDER"]));
            }
            set {
                this["FOR_FINAL_SYNC_FOLDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SIDC-1-2-1-1")]
        public string BRANCH_CODE {
            get {
                return ((string)(this["BRANCH_CODE"]));
            }
            set {
                this["BRANCH_CODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WHC0003")]
        public string WAREHOUSE {
            get {
                return ((string)(this["WAREHOUSE"]));
            }
            set {
                this["WAREHOUSE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AR_KNP_4")]
        public string AR_KNP_STORED {
            get {
                return ((string)(this["AR_KNP_STORED"]));
            }
            set {
                this["AR_KNP_STORED"] = value;
            }
        }
    }
}
